config/routes.rb
WebhookRails::Engine.routes.draw do
  root 'webhooks#index'
  resources :webhooks
end

app/models/webhook_rails/application_record.rb
module WebhookRails
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/webhook_rails/webhook.rb
module WebhookRails
  class Webhook < ApplicationRecord
    validates :name, :type, presence: true
    validates :token, presence: true, if: -> { type == Webhooks::TokenAuth.name }
    validates :username, :password, presence: true, if: -> { type == Webhooks::BasicAuth.name }
    validates :url, presence: true, format: { with: %r{\A^(https?\://)?[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,6}((/|\?)\S*)?$\z} }

    def self.types
      [['Basic Auth', Webhooks::BasicAuth.name], ['Token Auth', Webhooks::TokenAuth.name]]
    end

    def notify(_params = {})
      raise 'you have to implement in subclass'
    end
  end
end

app/models/webhook_rails/webhooks/basic_auth.rb
module WebhookRails
  module Webhooks
    class BasicAuth < ::WebhookRails::Webhook
      def notify(params = {})
        RestClient::Request.execute method: :post, payload: params, url: url, timeout: 30, user: username, password: password
      end
    end
  end
end

app/models/webhook_rails/webhooks/token_auth.rb
module WebhookRails
  module Webhooks
    class TokenAuth < ::WebhookRails::Webhook
      def notify(params = {})
        RestClient::Request.execute method: :post, payload: params, url: url, timeout: 30, headers: { Authorization: "Token token=#{token}" }
      end
    end
  end
end

app/controllers/webhook_rails/application_controller.rb
module WebhookRails
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/webhook_rails/webhooks_controller.rb
require_dependency "webhook_rails/application_controller"

module WebhookRails
  class WebhooksController < ApplicationController
    before_action :set_webhook, only: [:show, :edit, :update, :destroy]

    # GET /webhooks
    def index
      @webhooks = Webhook.all
    end

    # GET /webhooks/1
    def show
    end

    # GET /webhooks/new
    def new
      @webhook = Webhook.new
    end

    # GET /webhooks/1/edit
    def edit
    end

    # POST /webhooks
    def create
      @webhook = Webhook.new(webhook_params)

      if @webhook.save
        redirect_to @webhook, notice: 'Webhook was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /webhooks/1
    def update
      if @webhook.update(webhook_params)
        redirect_to @webhook, notice: 'Webhook was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /webhooks/1
    def destroy
      @webhook.destroy
      redirect_to webhooks_url, notice: 'Webhook was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_webhook
        @webhook = Webhook.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def webhook_params
        params.require(:webhook).permit(:name, :token, :username, :password, :url, :type)
      end
  end
end

app/helpers/webhook_rails/application_helper.rb
module WebhookRails
  module ApplicationHelper
  end
end

app/helpers/webhook_rails/webhooks_helper.rb
module WebhookRails
  module WebhooksHelper
  end
end

app/views/layouts/webhook_rails/application.html.haml
!!!
%html
  %head
    %title Webhook rails
    = csrf_meta_tags
    = csp_meta_tag

    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.7.0/css/all.css", :integrity => "sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ", :rel => "stylesheet"}

    = stylesheet_link_tag    "webhook_rails/application", media: "all"
    = javascript_include_tag "webhook_rails/application", media: "all"

  %body#webhooks
    = yield

app/views/webhook_rails/webhooks/_form.html.haml
/ = form_with(model: webhook, local: true) do |form|
/   - if webhook.errors.any?
/     #error_explanation
/       %h2
/         = pluralize(webhook.errors.count, "error")
/         prohibited this webhook from being saved:
/       %ul
/         - webhook.errors.full_messages.each do |message|
/           %li= message
/   .field
/     = form.label :name
/     = form.text_field :name
/   .field
/     = form.label :token
/     = form.text_field :token
/   .field
/     = form.label :username
/     = form.text_field :username
/   .field
/     = form.label :password
/     = form.text_field :password
/   .field
/     = form.label :url
/     = form.text_field :url
/   .field
/     = form.label :type
/     = form.text_field :type
/   .actions
/     = form.submit

.w-50.view-center
  = simple_form_for @webhook.becomes(WebhookRails::Webhook) do |f|
    = f.input :name, label: t('webhook.name')
    = f.input :url, label: t('webhook.url')
    = f.input :type, collection: WebhookRails::Webhook.types, input_html: { class: 'type' }, label: t('webhook.type'), include_blank: false
    .types{'data-type' => 'WebhookRails::Webhooks::TokenAuth'}
      = f.input :token, label: t('webhook.token')
    .types{'data-type' => 'WebhookRails::Webhooks::BasicAuth'}
      = f.input :username, label: t('webhook.username')
      = f.input :password, label: t('webhook.password')

    .actions
      = f.submit t('shared.save'), class: 'btn btn-primary'
      = link_to t('shared.cancel'), webhooks_path, class: 'btn btn-secondary'

app/views/webhook_rails/webhooks/edit.html.haml
#content
  %nav.navbar.navbar-expand-lg.navbar-light.bg-light
    .container-fluid
      %h3= t('webhook.edit_webhook')

  = render 'form'

app/views/webhook_rails/webhooks/index.html.haml
.d-flex.justify-content-center.py-4
  .w-75
    .d-flex.justify-content-end
      = link_to '+ Add New', new_webhook_path, class: 'btn btn-primary mb-4'

    %p#notice= notice
    %h1 Webhooks
    %table.table
      %thead
        %tr
          %th= t('webhook.name')
          %th= t('webhook.url')
          %th= t('webhook.type')
          %th
      %tbody
        - @webhooks.each do |webhook|
          %tr
            %td= webhook.name
            %td= webhook.url
            %td= webhook.type
            %td
              = link_to edit_webhook_path(webhook), class: "btn-circle btn-sm btn-warning text-decoration-none mr-1" do
                %i.fas.fa-edit

              = link_to webhook_path(webhook), method: :delete, data: { confirm: 'Are you sure to delete this form?'}, class: 'btn-circle btn-sm btn-danger text-decoration-none' do
                %i.fas.fa-trash

app/views/webhook_rails/webhooks/new.html.haml
#content
  %nav.navbar.navbar-expand-lg.navbar-light.bg-light
    .container-fluid
      %h3= t('webhook.new_webhook')

  = render 'form'

app/views/webhook_rails/webhooks/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @webhook.name
%p
  %strong Token:
  = @webhook.token
%p
  %strong Username:
  = @webhook.username
%p
  %strong Password:
  = @webhook.password
%p
  %strong Url:
  = @webhook.url
%p
  %strong Type:
  = @webhook.type
= link_to 'Edit', edit_webhook_path(@webhook)
|
\#{link_to 'Back', webhooks_path}